### PR TITLE
Support writing and reading NRRD header quoted string lists for label…

### PR DESCRIPTION
**Pull request by pcs-dan**
This feature was previously marked in the source code as 'TODO'.

### CODE REVIEW

**Comment by addisonElliott** [comment]
Hello, thanks for the PR. At a first glance, it looks good. Some unit tests would be a good thing to add.

~~On a more conceptual level, I'm not sure if making the three fields (labels, units, space units) **always** be a quoted string list is preferred.~~

Well, according to the NRRD spec, I suppose those three types should be surrounded by quotations ([source](http://teem.sourceforge.net/nrrd/format.html#spaceorigin))

**Comment by pcs-dan** [comment]
Thanks! I will take a look at adding unit tests.

**Comment by addisonElliott** [comment]
Also, I'm not sure if your code does this, but we probably want to remain backwards compatible in the sense that we should correctly parse the "quoted string list"'s correctly even if there are no quotes. In other words, fallback to just a string list if there are no quotes in the quoted string list.

**Comment by addisonElliott** [comment]
@pcs-dan Just checking up on your progress, any luck with creating unit tests?

If you don't or won't have the time, I may be able to create some and finish this PR up in the next few weeks.

**Comment by pcs-dan** [comment]
@addisonElliott I am sorry about the delay, I haven't had any time. I will try to add the tests in the next week.

**Comment by addisonElliott** [comment]
It's no problem, I just wanted to make sure you were still up for the task. Take your time

**Pull request merged**
