### PR TITLE
Fix key-value writing: no space allowed after ':=' identifier

### PR DESCRIPTION
**Pull request by ihnorton**
This was changed in https://github.com/mhe/pynrrd/pull/57

but per the NRRD documentation: http://teem.sourceforge.net/nrrd/format.html#general.2

"""
Each of the "<key>:=<value>" lines specifies a key/value pair in the nrrd. These can appear in NRRD0002 (and higher version) files, but not NRRD0001 files. The key and value strings are delimited by the first ":=" to appear on the line: any spaces before or after ":=" are assumed part of the key or value, respectively.
"""

### CODE REVIEW

**Comment by addisonElliott** [comment]
Good catch! 👍 

Do you think we should **not** remove whitespace from the key/value pairs when reading NRRD files? Personally, I lean towards no because I can't think of any useful reason of having whitespace in the value.

And, when I merge this in (I'll try to tonight), I'll probably wait to release the next version unless you really need these changes now. Hopefully a few more PRs come in soon and I can make a larger release.

**Comment by ihnorton** [comment]
> Do you think we should not remove whitespace from the key/value pairs when reading NRRD files? Personally, I lean towards no because I can't think of any useful reason of having whitespace in the value.

Agree, try to stick to spec when possible. I think some readers de-facto allow whitespace after the `:=` (e.g. if using `>>` operator to read whitespace-separated values in C++) but some software we use does not.

**Comment by tashrifbillah** [comment]
Hi @addisonElliott , can we get a release incorporating @ihnorton 's latest changes?
The release 0.3.4 does not have Isaiah's latest commit.

**Comment by addisonElliott** [comment]
Sure, I'll release a new version tonight.

**Comment by tashrifbillah** [comment]
Thanks @addisonElliott . We have also switched to the release version.

**Pull request merged**
