### PR TITLE
Compare test Numpy arrays using Numpy.testing module

### PR DESCRIPTION
**Pull request by addisonElliott**
The previous method was converting to a byte string and comparing the strings. The main issue is that if the assertion fails, there will be no useful information in the trace about the data because it's one large string. By using Numpy's testing module, it will report statistics about how far off the matrix is, size of matrix and where the values are mismatched.

### CODE REVIEW

**Comment by addisonElliott** [comment]
@mhe Thanks for accepting some of my PRs. Have you had a chance to look at these other two that I have remaining? They're pretty simple and easy ones.

**Comment by mhe** [comment]
@addisonElliott  I did have a look (add they look very useful, thanks again!), but had some merge conflicts that weren't so quick to resolve for me at the time. Can you maybe resolve the conflicts and update the PRs?

**Comment by addisonElliott** [comment]
Happy to help! This is a great, simple library that I've found a lot of use in.

I've fixed the merge conflicts. I understand that it's 10x easier to fix merge conflicts when you're the person who wrote the code...

I **don't** think the two remaining PRs should conflict with each other much, however I could be wrong. The biggest issue is that the tests are all in one file so that is what causes the merge conflicts..

**Comment by mhe** [comment]
@addisonElliott No further conflicts, thanks again!

**Pull request merged**
