### PR TITLE
Cherry pick from nocnokneo

### PR DESCRIPTION
**Pull request by nocnokneo**
Here are the fixes/improvements from my pynrrd fork that I never got around pushing back upstream (until now). Rebased against current master.

Resolves issue #15

### CODE REVIEW

**Comment by nocnokneo** [comment]
I also added Travis CI support to this pull request so the unit tests get run automatically. Here's an example running against my pull request branch:

https://travis-ci.org/nocnokneo/pynrrd/builds/75661257

**Comment by mhe** [comment]
That's great, thanks! I will review them and merge them asap.

**Comment by nocnokneo** [comment]
Glad to help!

@mhe Now that 6a16370 is merged, it would be nice to setup a Travis CI job for the mhe/pynrrd repository.

**Comment by mhe** [comment]
I agree and will look into that. Thanks!

**Comment by mhe** [comment]
@nocnokneo Travis CI is now configured for mhe/pynrrd. Thanks again for the tests!

**Pull request merged**
