### PR TITLE
ENH: Added testNrrd program

### PR DESCRIPTION
**Pull request by aghayoor**
testNrrd.py defines "nrrdDWIHeader" class that helps us to read a DWI nrrd file using pynrrd.
Then, the DWI nrrd file is converted to Nifti using DWIConvert and is read by dipy.
The gradient table and b-values are compared to verify that the files read by both methods are compatible.
Also, we do something interesting with manipulating DWI data (i.e. average close gradients) and write the output file to disk in nrrd format again and verify the output.

### CODE REVIEW

**Comment by aghayoor** [comment]
@hjmjohnson Please check this pull request. Thank you.

**Comment by hjmjohnson** [comment]
@aghayoor This looks good to me.  Thank you for the extensive testing.

@mhe I think this patch set provides important elements for using DWI imaging data in nrrd format with python.  Would you please consider merging it?

Thanks,
Hans

**Comment by mhe** [comment]
@hjmjohnson I'm definitely interested in improving support for DWI imaging data in pynrrd. However, I'm still a bit confused what exactly the testNrrd.py file provides. It appears that it does multiple things? I see code that provides useful code for dealing with DWI (meta) data, code to support some sort of conversion tool, and code to test certain functionality. In addition I'm afraid the name "testNrrd.py" may give (new) users of the pynrrd library the impression that this is a file that tests the whole pynrrd library (as also discussed earlier, see #14).

I might have misinterpreted things here (if that is the case, please correct me), but what do you think of the following proposal?
- Rename testNrrd.py to something like "dwi_nrrd.py" or "nrrd_dwi.py" (other suggestions welcome)
- Move the code from testNrrd.py that provides a conversion tool to a separate file (for example "dwiconvert.py" or something like that), perhaps in a separate "tools/" directory.
- Move the code for testing the DWI functionality to a separate file in the "tests/" directory.
- Move the shell-script for testing to the "tests/" directory (with a bit more comments explaining what it is for and who would be interesting in running it/requirements for being able to run it).

**Comment by hjmjohnson** [comment]
@mhe I am sorry, that should not be included.  That was code we used to develop the solution that ensures that the solution worked for several corner cases that we have run into over the years in the NAMIC project.

@aghayoor, Please review @mhe's excellent suggestions and follow his advice in the previous comment.

**Comment by hjmjohnson** [comment]
@aghayoor I need this done ASAP.  I have people here who need this, but it needs to be merged.

**Comment by aghayoor** [comment]
@hjmjohnson @mhe Please review modified patch set. In this new patch set, the support for DWI imaging is provided in a new module named "dwi_nrrd", and extensive testing for this new module is provided in /tests directory.

**Comment by mhe** [comment]
@hjmjohnson @aghayoor Thanks, I'm looking into it.

**Comment by mhe** [comment]
@aghayoor @hjmjohnson What is your opinion on the following? I propose to turn your contributions on handling dwi files into a proper submodule of nrrd ("nrrd.dwi"). This way, users of the library can for example refer to the function `nrrd.dwi.ReadNAMICDWIFromNrrd`.

After some reading and experimentation I believe this can be done as follows:
- Rename `nrrd_dwi.py` to `dwi.py`
- Edit `setup.py`: remove the line with `py_modules=` and add the following two lines instead:
```
      packages=['nrrd'],
      package_dir={'nrrd': ''},
```
- Add a `__init__.py` with the following content:
```
# import all of nrrd
from nrrd import *
# import sub-module for handling nrrd files with dwi content
import dwi
```
What do you think?

As for the tests, I'll for now take your word on that it all works as I cannot test the code myself. It would be nice if there eventually would be a couple of small (synthetic?) test files so that we can automatically test also that part of the library.

**Comment by hjmjohnson** [comment]
Martin,

 

This sounds like a good plan.  Ali is starting a new job, and he will have limited time to do this.  Would it be possible for you to implement the proposed changes?

 

Thanks,

Hans

 

 

--

**Comment by mhe** [comment]
@hjmjohnson Yes, I'll do that.

**Comment by hjmjohnson** [comment]
Spectacular.  Let me know once that  is completed.

 

Hans

**Comment by mhe** [comment]
I merged the commits for DWI support into a dwi branch, on top of which I added some changes puts the DWI support into a submodule. @hjmjohnson @aghayoor Could you check whether these changes also work for you? If you find I didn't break things I'll merge this feature-branch into master and create a new release (v0.3.0).

**Comment by mhe** [comment]
@hjmjohnson @aghayoor Are you still interested in the DWI support? I added the DWI support in a feature branch ("dwi"), but I will not merge this into the master branch until I know for sure this works. However, I do not have the means to test it as I do not have proper test data.
For now I will leave things as is.

**Comment by hjmjohnson** [comment]
We are, and we have tested and it works.  

 

We have been using the branch, but would love this be a part of the master tree.

 

Thanks,

Hans

**Comment by aghayoor** [comment]
Hi, I remember I tested the dwi branch after your changes to put the DWI support into a submodule. Everything was working well on our test data.

Thanks,
Ali

**Comment by mhe** [comment]
@hjmjohnson @aghayoor Ok, thanks! While looking at it again, I wonder about the following. As the DWI support you added is now a proper (sub)module, wouldn't it maybe make more sense to host (and maintain) this `dwi` module in your own (github) namespace?

**Pull request merged**
