### PR TITLE
Add capabilities for reading DWI 4D data for NRRD files

### PR DESCRIPTION
**Pull request by hjmjohnson**
The National Alliance for Medical Image Computing (NAMIC) community uses the nrrd file format for DWI data processing.  These patches provide the infrastructure necessary reading/writing NAMIC DWI into python and interacting with nibabel, and dipy toolkits.

### CODE REVIEW

**Comment by hjmjohnson** [comment]
@mhe This patch set should be backwards compatible with the current use, but will also allow reading the meta data for DWI 4D data sets in a way that allows pynrrd to be used with dipy and nibabel.

It would be great if these could be merged in to the upstream path to avoid too much divergence between projects.

PS:  Thank you for the great infrastructure.

**Comment by mhe** [comment]
Thanks a lot for all these fixes and enhancements. I'll review them ASAP!

**Comment by hjmjohnson** [comment]
@mhe  Thanks for your consideration.  This will be a huge benefit to the neuro-imaging community.

**Comment by hjmjohnson** [comment]
@mhe There will be a developer hangout this week to discuss incorporation of new imaging converters for nibabel.  It would be great to add nrrd to the default reading capabilities of nrrd.  Do you think that you can review and comment on this patch set soon?

**Comment by mhe** [comment]
@hjmjohnson The changes to nrrd.py look good to me (thanks!). The only thing I'm worried about is the test code. While good to have it, it is for a specific use case, which might confuse new users. I would propose renaming testNrrd.py such that it is clear what is being tested (do you have a suggestion?). I would also opt to not to include RUN_testNrrd.sh as it contains user-specific file paths.

**Comment by hjmjohnson** [comment]
@mhe I have removed both tests.  They both depend upon exterternal conversion packages to verify that the results were compliant with nibabel, nipype, and the NAMIC community test data sets.  Those tests could not be made self contained.  I've put them in a separate private branch so that we will have them if needed in the future.

Thank you for your consideration.

**Comment by mhe** [comment]
@hjmjohnson Thanks again for your contributions!

**Pull request merged**
